apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/giladravid16/assisted-service?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "konflux-test"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: assisted-service-saas-konflux-test
    appstudio.openshift.io/component: assisted-service-saas-konflux-test
    pipelines.appstudio.openshift.io/type: build
  name: assisted-service-saas-konflux-test-on-pull-request
  namespace: rh-ee-gravid-tenant
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/giladravid16/konflux-pipelines.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/service-component-pipeline.yaml"
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/rh-ee-gravid-tenant/assisted-service-saas-konflux-test/assisted-service-saas-konflux-test:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: Dockerfile.assisted-service
    - name: path-context
      value: .
  taskRunTemplate:
    serviceAccountName: build-pipeline-assisted-service-saas-konflux-test
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
