apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/giladravid16/assisted-service?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "konflux-test"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: assisted-service-acm-konflux-test
    appstudio.openshift.io/component: assisted-service-acm-konflux-test
    pipelines.appstudio.openshift.io/type: build
  name: assisted-service-acm-konflux-test-on-push
  namespace: rh-ee-gravid-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/rh-ee-gravid-tenant/assisted-service-acm-konflux-test/assisted-service-acm-konflux-test:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
    - name: dockerfile
      value: Dockerfile.assisted-service-rhel9-mce
    - name: path-context
      value: .
    - name: build-args
      value:
        - release={{target_branch}}
        - version={{revision}}
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '[{"type": "gomod", "path": "."}, {"type": "rpm", "path": "./rpm-prefetching/assisted-service-rhel9/"}]'
    - name: build-source-image
      value: "true"
    - name: additional-tags
      value: ["latest"]
    - name: sast-snyk-check-args
      value: "--project-name=assisted-service --report --org=3e6fd93b-b325-49dd-8a33-432a0160ab66"
    - name: sast-snyk-check-ignore-file-paths
      value: "tools/wait_for_assisted_service.py,tools/deploy_wiremock.py"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/giladravid16/konflux-pipelines.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/product-component-pipeline.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-assisted-service-acm-konflux-test
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
